# Generated by Django 4.2.2 on 2023-06-13 20:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_url_storage_video_video_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
            preserve_default=False,
        ),
    ]
