# Generated by Django 4.2.2 on 2023-06-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_video_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
