# Generated by Django 4.2.2 on 2023-06-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_video_uploaded_by_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
