# Generated by Django 4.2.2 on 2023-06-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
